app = "my-proxy-app" # keep your app name here

primary_region = "cdg" # or a region closer to your users

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080" # make sure your app listens on this port

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 150
