app = "proxy-"
primary_region = "ams"  

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  GO_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[http_service.http_checks]]
    interval = "15s"
    timeout = "5s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    grace_period = "5s"
    restart_limit = 3

[metrics]
  port = 8080
  path = "/metrics"

[deploy]
  strategy = "rolling"
  max_unavailable = 0

[vm]
  memory = "1gb"
  cpus = 2
  kernel_args = ["net.ipv4.tcp_keepalive_time=60", "net.ipv4.tcp_keepalive_intvl=30"]
