# .env file - for local testing ONLY
# These values MUST be set as Fly.io secrets using flyctl secrets set
# Example values:
# fly.toml file for your application
app = "app.py"

[env]
# The environment variables are handled as secrets in Fly.io
