app = "my-proxy-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  SSH_USER = "sshkit-7104485144"
  SSH_PASSWORD = "123"
  SSH_ADDR = "ssh-fr1.sshkit.org:443"
  ENCRYPTION_KEY = "your_strong_16_byte_key"
  AUTH_SECRET = "your_auth_token"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  session_affinity = "http_request_header"
  session_affinity_cookie_name = "X-FB-Trace-ID"

[checks]
  [checks.http]
    type = "http"
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/health"
    timeout = "2s"
